@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QzIiwiZW1haWwiOiJqYWtlMkBqYWtlLmpha2UiLCJpYXQiOjE2ODY0MDU2OTd9.ABzS2B6TFyLE7LubbwpK1IhNbaG6DcnMrVDYNc6qHjU


@token1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwiZW1haWwiOiJqYWtlMUBqYWtlLmpha2UiLCJpYXQiOjE2MjE4OTA4MDB9.fx5nD6_MjXLPzO-QQswu22HsOwDivI_3-AU0fIoRv64

### 注册
POST /api/users
host: {{host}}
content-type: {{contentType}}

{
  "user":{
    "email": "jake2@jake.jake",
    "password": "jakejake",
    "username": "test3"
  }
}
### 登录
POST /api/users/login
host: {{host}}
content-type: {{contentType}}

{
  "user":{
    "email": "jake2@jake.jake",
    "password": "jakejake"
  }
}


### 查看当前用户
GET /api/user
host: {{host}}
content-type: {{contentType}}
Authorization: Token {{token}}

###
PATCH  /api/user
host: {{host}}
content-type: {{contentType}}
Authorization: Token {{token}}

{
  "user":{
    "bio": "bio ",
    "image":"/b.png",
    "info": "asdfasdf"
  }
}

###
GET /api/profiles/test3
host: {{host}}
content-type: {{contentType}}
Authorization: Token {{token1}}

###
POST /api/profiles/test3/follow
host: {{host}}
content-type: {{contentType}}
Authorization: Token {{token}}

###
POST /api/articles
host: {{host}}
content-type: {{contentType}}
Authorization: Token {{token}}

{
  "article": {
    "title": "How to tt train your dragon af c",
    "description": "Ever wonder how?",
    "body": "You have to believe",
    "tagList": ["reactjs", "angularjs", "cs", "js" ,"c","dragons"]
  }
}
###
GET /api/articles?author=test
host: {{host}}
content-type: {{contentType}}



###
POST /api/articles/how-to-train-your-dragon-af-c/favorite
host: {{host}}
content-type: {{contentType}}
Authorization: Token {{token}}

###
GET /api/articles/how-to-train-your-dragon-af-c/comments
host: {{host}}
content-type: {{contentType}}
Authorization: Token {{token}}

###
POST  /api/articles/how-to-train-your-dragon-af-c/comments
host: {{host}}
content-type: {{contentType}}
Authorization: Token {{token1}}

{   
    "comment":{
    "body":"comments to articles"
}
}

###
GET /api/tags
host: {{host}}
content-type: {{contentType}}

###